version: '3'

services:

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: /bin/sh
    environment: 
      - PG_DATABASE=speed_test
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
      - PG_HOST=db
      - PG_PORT=5432
    volumes:
      - ./app/speed_monitor:/speed_monitor
    tty: true

  db:
    image: arm32v6/postgres:13.1-alpine
    environment: 
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=speed_test
    ports: 
      - 5432:5432